name = "duramaxpi"
main = "src/index.ts"
compatibility_date = "2026-04-21"

[assets]
directory = "./dist"

[[r2_buckets]]
binding = "plataformaing"
bucket_name = "plataformaing"

[observability]
enabled = true
